
#################################### Grafana Configuration ####################################
# Everything has defaults so you only need to uncomment things you want to change

[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
data = /var/lib/grafana

# Temporary files in `data` directory older than `temp_data_lifetime` will be removed
temp_data_lifetime = 24h

# Directory where grafana can store logs
logs = /var/log/grafana

# Directory where grafana will automatically scan and look for plugins
plugins = /var/lib/grafana/plugins

# folder that contains provisioning config files that grafana will apply on startup
provisioning = /etc/grafana/provisioning

#################################### Server ####################################
[server]
enable_gzip = true
cert_file = /etc/grafana/grafana.crt
cert_key = /etc/grafana/grafana.key

# Protocol (http, https, socket)
protocol = https

# The ip address to bind to, empty will bind to all interfaces
http_addr =

# The http port to use
http_port = 3001

# The public facing domain name used to access grafana from a browser
# domain =  0.0.0.0

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true

# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/
# root_url = https://localhost:3001
# Log web requests
router_logging = false

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = true

#################################### Database ####################################
[database]
# You can configure the database connection by specifying type, host, name, user and password
# as separate properties or as on string using the url property.

# Either "mysql", "postgres" or "sqlite3", it's your choice
[database]
;type = mysql
;host = mysql:3305
;name = database_grafana
;user =
;password =

# For "postgres" only, either "disable", "require" or "verify-full"
ssl_mode = disable

#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin
;admin_password = admin_password
# If you want to embed grafana into an iframe for example
allow_embedding = false

# used for signing
secret_key = SW2YcwTIb9zpOOhoPsMm

#################################### Snapshots #######################(optional)############
[snapshots]
# snapshot sharing options
external_enabled = true
external_snapshot_url = https://snapshots-origin.raintank.io
external_snapshot_name = Publish to snapshot.raintank.io

#################################### Dashboards Provisioning #######################(optional)############
[dashboard]
# Path to directory containing dashboards you want to load
path = /var/lib/grafana/dashboards

#################################### Users ####################################
[users]
# disable user signup / registration
allow_sign_up = false

default_theme = dark

# allow user self assign roles
allow_user_self_assign_role = false

#################################### Auth Proxy #######################(optional)############
[auth.proxy]
enabled = false

#################################### Alerting ####################################
[unified_alerting]
# make sure alerting is enabled
enabled = true

#################################### SMTP / Emailing #######################(optional)############
[smtp]
;enabled = true
;host = smtp.example.com:587
;user = your_email@example.com
;# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
;password = your_smtp_password
;;cert_file =
;;key_file =
;skip_verify = false
;from_address = grafana@example.com
;from_name = Grafana

#################################### Logging ####################################
[log]
# Either "console", "file", "syslog". Default is console and file
mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
level = info

[log.console]
level = info

[log.file]
level = info
log_rotate = true
max_lines = 1000000
max_size_shift = 28
daily_rotate = true
max_days = 7

#################################### Metrics ####################################
[metrics]
# Disable / Enable internal metrics
enabled = true

# Publish interval
interval_seconds = 10

#################################### Grafana.com API #######################(optional)############
[grafana_com]
# URL used to communicate with the Grafana backend server.
url = https://grafana.com

[plugins]
allow_loading_unsigned_plugins =

